apiVersion: core.choreo.dev/v1beta1
kind: Component
metadata:
  name: tom-depp-bot
  description: Tom Depp - your chaotic Telegram friend
spec:
  type: Service
  source:
    language: nodejs
    version: "20.x"
  build:
    buildCommand: npm install
  run:
    runCommand: node index.js
  endpoints:
    - name: health
      port: 8080
      type: REST
      networkVisibility: Project
      context: /
